

// Auto generated SYCL kernel wrapper used to migration kernel function pointer.
// auto generated by generate.py
// clang-format off

#define ONEAPI_BACKEND_LEVEL_ZERO_EXT
#define DPCT_PROFILING_ENABLED
#include <sycl/sycl.hpp>
#include <dpct/dpct.hpp>
#include <c10/xpu/XPUStream.h>
#include "kernel.h"
#include "marlin_template.h"

namespace MARLIN_NAMESPACE_NAME {

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, true, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                 uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, true, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                 uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, false, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                  uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, false, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                  uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 2, 16, 4, false, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 2, 8, 4, false, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                  uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 3, 16, 4, false, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 3, 8, 4, false, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                  uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 4, 16, 4, false, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 4, 8, 4, false, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                  uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, true, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, true, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, false, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                    uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, false, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                    uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 2, 16, 4, false, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                     uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 2, 8, 4, false, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                    uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 3, 16, 4, false, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                     uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 3, 8, 4, false, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                    uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 4, 16, 4, false, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                     uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 4, 8, 4, false, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                    uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, true, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                  uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, true, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                  uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, false, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, false, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 2, 16, 4, false, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                    uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 2, 8, 4, false, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 3, 16, 4, false, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                    uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 3, 8, 4, false, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 4, 16, 4, false, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                    uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 4, 8, 4, false, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, true, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                  uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, true, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                  uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, false, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, false, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 2, 16, 4, false, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                    uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 2, 8, 4, false, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 3, 16, 4, false, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                    uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 3, 8, 4, false, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 4, 16, 4, false, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                    uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 4, 8, 4, false, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, true, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                  uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, true, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                  uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, false, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, false, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 2, 16, 4, false, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                    uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 2, 8, 4, false, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 3, 16, 4, false, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                    uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 3, 8, 4, false, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 4, 16, 4, false, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                    uint8_t *dpct_local);

template void Marlin<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 4, 8, 4, false, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS ,
                                                                                                                   uint8_t *dpct_local);


// wrapper

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, true, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, true, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, false, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS);

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, false, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 2, 16, 4, false, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 2, 8, 4, false, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 3, 16, 4, false, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 3, 8, 4, false, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 4, 16, 4, false, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 4, 8, 4, false, pipe_stages, true, false, 0, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, true, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, true, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, false, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, false, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 2, 16, 4, false, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 2, 8, 4, false, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS);

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 3, 16, 4, false, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 3, 8, 4, false, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 4, 16, 4, false, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 4, 8, 4, false, pipe_stages, false, false, -1, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, true, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, true, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, false, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, false, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS);

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 2, 16, 4, false, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 2, 8, 4, false, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 3, 16, 4, false, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 3, 8, 4, false, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS);

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 4, 16, 4, false, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 4, 8, 4, false, pipe_stages, false, false, 2, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, true, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, true, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, false, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, false, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 2, 16, 4, false, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS);

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 2, 8, 4, false, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 3, 16, 4, false, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS);

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 3, 8, 4, false, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 4, 16, 4, false, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 4, 8, 4, false, pipe_stages, false, false, 4, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, true, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, true, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 1, 8, 8, false, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 1, 8, 4, false, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS );

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 2, 16, 4, false, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS);

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 2, 8, 4, false, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS);

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 3, 16, 4, false, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS);

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 3, 8, 4, false, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS);

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 256, 4, 16, 4, false, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS);

template void Marlin_wrapper<sycl::ext::oneapi::bfloat16, sglang::kU8B128.id(), 128, 4, 8, 4, false, pipe_stages, false, false, 8, false>( MARLIN_KERNEL_PARAMS);


}
